/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_embe2020_project_MainActivity */

#ifndef _Included_com_embe2020_project_MainActivity
#define _Included_com_embe2020_project_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_embe2020_project_MainActivity
 * Method:    ledwrite
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_embe2020_project_MainActivity_ledwrite
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_embe2020_project_MainActivity
 * Method:    controlswitch
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_embe2020_project_MainActivity_controlswitch
  (JNIEnv *, jobject);

/*
 * Class:     com_embe2020_project_MainActivity
 * Method:    controldotfnd
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_embe2020_project_MainActivity_controldotfnd
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_embe2020_project_MainActivity
 * Method:    deviceclear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_embe2020_project_MainActivity_deviceclear
  (JNIEnv *, jobject);

/*
 * Class:     com_embe2020_project_MainActivity
 * Method:    controltextlcd
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_embe2020_project_MainActivity_controltextlcd
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
