/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_embe2020_project_MainActivity_Thread_dot */

#ifndef _Included_com_embe2020_project_MainActivity_Thread_dot
#define _Included_com_embe2020_project_MainActivity_Thread_dot
#ifdef __cplusplus
extern "C" {
#endif
#undef com_embe2020_project_MainActivity_Thread_dot_MIN_PRIORITY
#define com_embe2020_project_MainActivity_Thread_dot_MIN_PRIORITY 1L
#undef com_embe2020_project_MainActivity_Thread_dot_NORM_PRIORITY
#define com_embe2020_project_MainActivity_Thread_dot_NORM_PRIORITY 5L
#undef com_embe2020_project_MainActivity_Thread_dot_MAX_PRIORITY
#define com_embe2020_project_MainActivity_Thread_dot_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
